name: gestao_vagas Application

on:
  push:
    branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up JAVA
              uses: actions/setup-java@v2
              with:
                  distribution: temurin
                  java-version: 17

            - name: Build with Maven
              run: mvn clean install

            - name: Login Docker
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gestao_vagas .

            - name: Push Docker image
              run: docker push ${{ secrets.DOCKER_USERNAME }}/gestao_vagas
